name: Validate device JSONs

on: [push, pull_request]

jobs:
  verify-jsons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Validate device JSONs
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
           INPUT_SCHEMA: $GITHUB_WORKSPACE/schemas/device_schema.json
           INPUT_JSONS: $GITHUB_WORKSPACE/devices/mimameid.json,$GITHUB_WORKSPACE/devices/yggdrasil.json